version: '3.8'

services:
  cart:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: CartDB
    volumes:
      - /var/lib/docker/volumes/CartStorage/_data:/var/lib/postgresql/data

volumes:
  CartStorage:
